### ISSUE TITLE
README

### ISSUE THREAD

**Issue by omidb** [768bit/vue-sock-rpc#1]
Hi,

Is there any documentation available? 

Thanks

**Comment by spuddleziz** [comment]
Hi,

I have added an initial README for you. I wrote this to support an existing back end system we are improving. Was originally using a golang/gopherjs and then a wasm setup but Vue just makes our lives easier.

If you have any questions let me know but it wasnt really meant for use outside our implementation. I hope it helps its worked rather well for us.

The important thing is that your back end Socket.IO server respond with, at the very least, the request ID supplied by this library.

I have included other fields like session keys and payloads and other stuff but for basic messages you only really need a payload and the aforementioned request ID and everything should work as required.

**Comment by spuddleziz** [comment]
This is the back end implementation we used: https://github.com/768bit/bufalus

**Comment by omidb** [comment]
Thanks
